<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>oculus_reader</name>
  <version>0.0.1</version>
  <description>ROS 2 Quest teleoperation input and IK adapter for supported robot arms</description>

  <maintainer email="2906212119@qq.com">syh</maintainer>
  <author email="2906212119@qq.com">syh</author>
  <license>Apache-2</license>
  <url type="repository">https://github.com/saiyuhang123/QuestArmTeleop</url>
  <url type="bugtracker">https://github.com/saiyuhang123/QuestArmTeleop/issues</url>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>

  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>tf2_ros</depend>
  
  <depend>ament_index_python</depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>canopen_arm_bringup</exec_depend>
  <exec_depend>canopen_arm_description</exec_depend>
  <exec_depend>pinocchio</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-scipy</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
